-- The exhibitor floor: 32 booths and 4 sponsors, from the
-- committee's booth sheet.
-- GENERATED by scripts/booths_migration.py — edit the sheet, not this file.
--
-- This replaces the earlier booth migration, which was built from a sheet the
-- committee has since redrawn. Idempotent in both directions:
--   · an exhibitor already present under its code is left alone, keeping its
--     scanner login and every scan it has collected;
--   · an exhibitor that is NOT in the sheet is removed, but only when nobody
--     has scanned it — a database in use is never quietly emptied.
--
-- Scanner accounts land on the default password (booth-<code>@natcon.id /
-- SEED_PASSWORD): the rows below carry a placeholder hash nobody can sign in
-- with, and the API's seeder rewrites it on the next start. Set
-- SEED_PASSWORD before the event.

-- Scanner logins first: one tenant user per booth.
INSERT INTO users (name, email, password_hash, role, company)
SELECT v.company, v.email, '$2a$10$SEEDPLACEHOLDERSEEDPLACEHOLDERSEEDPLACEHOLDERSEEDPLACEH', 'tenant', v.company
FROM (VALUES
    ('A1', 'SSCX International', 'Management Consultant', 'SI', 'booth', 'booth-a1@natcon.id'),
    ('A2', 'PT. ORIENTAL LOGISTICS INDONESIA', 'Freight Forwarder', 'PO', 'booth', 'booth-a2@natcon.id'),
    ('A3', 'PT. Venamon', 'Manufacturer', 'PV', 'booth', 'booth-a3@natcon.id'),
    ('A4', 'ToffeeDev', 'SEO & Digital Marketing', 'T', 'booth', 'booth-a4@natcon.id'),
    ('A5', 'Doxadigital', 'Digital Advertising', 'D', 'booth', 'booth-a5@natcon.id'),
    ('A6', 'PT Natural Spirit', 'Healthy Organic Foods', 'PN', 'booth', 'booth-a6@natcon.id'),
    ('A9', 'PT. Gunanusa Eramandiri Tbk', 'Manufacturer specializing in premium nut products and high-quality fruit solutions', 'PG', 'booth', 'booth-a9@natcon.id'),
    ('A10', 'PT Tanamera Mitra Sentosa', 'Coffee Wholesale', 'PT', 'booth', 'booth-a10@natcon.id'),
    ('A14', 'WIT.id', 'IT Consultants', 'W', 'booth', 'booth-a14@natcon.id'),
    ('A15', 'PT ForBis Asia Indonesia', 'HRIS Software & Payroll Services', 'PF', 'booth', 'booth-a15@natcon.id'),
    ('A16', 'CV WIRABUANA SAKTI', 'automotive and stainless paint', 'CW', 'booth', 'booth-a16@natcon.id'),
    ('A17', 'One Tax CM Pte Ltd', 'Company Secretary', 'OT', 'booth', 'booth-a17@natcon.id'),
    ('A18 & A20', 'GrasiaCare', 'Profesional Service Health Care', 'G', 'booth', 'booth-a18@natcon.id'),
    ('A19', 'Sinar Printing (PT Sinar Media Kreasi)', 'Printer', 'SP', 'booth', 'booth-a19@natcon.id'),
    ('A22', 'Paper.id', 'B2B Digital Invoicing & Payment', 'P', 'booth', 'booth-a22@natcon.id'),
    ('A23', 'inHARMONY Preventive Clinic', 'Health & Wellness', 'IP', 'booth', 'booth-a23@natcon.id'),
    ('A24', 'PT Documenta Corpora Technology', 'Legal Service Plan', 'PD', 'booth', 'booth-a24@natcon.id'),
    ('A25', 'Lisanna Online Accounting & Tax Consultant', 'Accounting & Tax Consultant', 'LO', 'booth', 'booth-a25@natcon.id'),
    ('A27', 'PT Zona Kreatif Indonesia', 'IT Custom Software Development', 'PZ', 'booth', 'booth-a27@natcon.id'),
    ('A30', 'ICUBE (Invoice ke PT)', 'eCommerce Web and App Solution', 'I(', 'booth', 'booth-a30@natcon.id'),
    ('A31', 'PT. Norita Flexindo', 'Flexible Packaging', 'PN', 'booth', 'booth-a31@natcon.id'),
    ('A32', 'Alps Wills Pte Ltd', 'Will writing', 'AW', 'booth', 'booth-a32@natcon.id'),
    ('A33', 'BOOKINGTOGO', 'Travel Agent', 'B', 'booth', 'booth-a33@natcon.id'),
    ('A34', 'PAKS (MM2H) SDN BHD', 'MM2H', 'P(', 'booth', 'booth-a34@natcon.id'),
    ('A36', 'CV. TRIANA BINTANG', 'Manufactur dan Distributor GENSET', 'CT', 'booth', 'booth-a36@natcon.id'),
    ('A37', 'LEKA (PT Tissor Indonesia)', 'Retail - Electronics', 'L(', 'booth', 'booth-a37@natcon.id'),
    ('A38', 'CV IT Pro Solutions', 'Sales Force Automation', 'CI', 'booth', 'booth-a38@natcon.id'),
    ('A42', 'PT. TSN Ariestama Jaya', 'Office Supplies', 'PT', 'booth', 'booth-a42@natcon.id'),
    ('A43', 'PT. Creative Media Indonesia', 'Electronics Retailer', 'PC', 'booth', 'booth-a43@natcon.id'),
    ('A44', 'KETAPANG INDAH HOTEL', 'HOTEL', 'KI', 'booth', 'booth-a44@natcon.id'),
    ('A46', 'PT Belanja Segar Indonesia', 'Food Supplier', 'PB', 'booth', 'booth-a46@natcon.id'),
    ('A47 & A48', 'Alpha leaders', 'Business Coaching', 'AL', 'booth', 'booth-a47@natcon.id'),
    ('B1', 'Bio Medika', 'Health & Wellness', 'BM', 'sponsor', 'booth-b1@natcon.id'),
    ('B2', 'Parahita Diagnostic Center', 'Health & Wellness Services', 'PD', 'sponsor', 'booth-b2@natcon.id'),
    ('B3', 'ProSnap', 'Business Consultant', 'P', 'sponsor', 'booth-b3@natcon.id'),
    ('C1', 'T Royal Medicalink Pharmalab & PT Aroma Bathi Indonesia', 'Pharmaceutical Manufacturing & Essential Oils', 'TR', 'sponsor', 'booth-c1@natcon.id')
) AS v (booth, company, category, initials, kind, email)
WHERE NOT EXISTS (SELECT 1 FROM users u WHERE u.email = v.email)
  AND NOT EXISTS (SELECT 1 FROM tenants t WHERE t.booth = v.booth);

INSERT INTO tenants (name, category, booth, initials, kind, description,
                     contact_name, chapter, owner_user_id)
SELECT v.company, v.category, v.booth, v.initials, v.kind, '', '', '', u.id
FROM (VALUES
    ('A1', 'SSCX International', 'Management Consultant', 'SI', 'booth', 'booth-a1@natcon.id'),
    ('A2', 'PT. ORIENTAL LOGISTICS INDONESIA', 'Freight Forwarder', 'PO', 'booth', 'booth-a2@natcon.id'),
    ('A3', 'PT. Venamon', 'Manufacturer', 'PV', 'booth', 'booth-a3@natcon.id'),
    ('A4', 'ToffeeDev', 'SEO & Digital Marketing', 'T', 'booth', 'booth-a4@natcon.id'),
    ('A5', 'Doxadigital', 'Digital Advertising', 'D', 'booth', 'booth-a5@natcon.id'),
    ('A6', 'PT Natural Spirit', 'Healthy Organic Foods', 'PN', 'booth', 'booth-a6@natcon.id'),
    ('A9', 'PT. Gunanusa Eramandiri Tbk', 'Manufacturer specializing in premium nut products and high-quality fruit solutions', 'PG', 'booth', 'booth-a9@natcon.id'),
    ('A10', 'PT Tanamera Mitra Sentosa', 'Coffee Wholesale', 'PT', 'booth', 'booth-a10@natcon.id'),
    ('A14', 'WIT.id', 'IT Consultants', 'W', 'booth', 'booth-a14@natcon.id'),
    ('A15', 'PT ForBis Asia Indonesia', 'HRIS Software & Payroll Services', 'PF', 'booth', 'booth-a15@natcon.id'),
    ('A16', 'CV WIRABUANA SAKTI', 'automotive and stainless paint', 'CW', 'booth', 'booth-a16@natcon.id'),
    ('A17', 'One Tax CM Pte Ltd', 'Company Secretary', 'OT', 'booth', 'booth-a17@natcon.id'),
    ('A18 & A20', 'GrasiaCare', 'Profesional Service Health Care', 'G', 'booth', 'booth-a18@natcon.id'),
    ('A19', 'Sinar Printing (PT Sinar Media Kreasi)', 'Printer', 'SP', 'booth', 'booth-a19@natcon.id'),
    ('A22', 'Paper.id', 'B2B Digital Invoicing & Payment', 'P', 'booth', 'booth-a22@natcon.id'),
    ('A23', 'inHARMONY Preventive Clinic', 'Health & Wellness', 'IP', 'booth', 'booth-a23@natcon.id'),
    ('A24', 'PT Documenta Corpora Technology', 'Legal Service Plan', 'PD', 'booth', 'booth-a24@natcon.id'),
    ('A25', 'Lisanna Online Accounting & Tax Consultant', 'Accounting & Tax Consultant', 'LO', 'booth', 'booth-a25@natcon.id'),
    ('A27', 'PT Zona Kreatif Indonesia', 'IT Custom Software Development', 'PZ', 'booth', 'booth-a27@natcon.id'),
    ('A30', 'ICUBE (Invoice ke PT)', 'eCommerce Web and App Solution', 'I(', 'booth', 'booth-a30@natcon.id'),
    ('A31', 'PT. Norita Flexindo', 'Flexible Packaging', 'PN', 'booth', 'booth-a31@natcon.id'),
    ('A32', 'Alps Wills Pte Ltd', 'Will writing', 'AW', 'booth', 'booth-a32@natcon.id'),
    ('A33', 'BOOKINGTOGO', 'Travel Agent', 'B', 'booth', 'booth-a33@natcon.id'),
    ('A34', 'PAKS (MM2H) SDN BHD', 'MM2H', 'P(', 'booth', 'booth-a34@natcon.id'),
    ('A36', 'CV. TRIANA BINTANG', 'Manufactur dan Distributor GENSET', 'CT', 'booth', 'booth-a36@natcon.id'),
    ('A37', 'LEKA (PT Tissor Indonesia)', 'Retail - Electronics', 'L(', 'booth', 'booth-a37@natcon.id'),
    ('A38', 'CV IT Pro Solutions', 'Sales Force Automation', 'CI', 'booth', 'booth-a38@natcon.id'),
    ('A42', 'PT. TSN Ariestama Jaya', 'Office Supplies', 'PT', 'booth', 'booth-a42@natcon.id'),
    ('A43', 'PT. Creative Media Indonesia', 'Electronics Retailer', 'PC', 'booth', 'booth-a43@natcon.id'),
    ('A44', 'KETAPANG INDAH HOTEL', 'HOTEL', 'KI', 'booth', 'booth-a44@natcon.id'),
    ('A46', 'PT Belanja Segar Indonesia', 'Food Supplier', 'PB', 'booth', 'booth-a46@natcon.id'),
    ('A47 & A48', 'Alpha leaders', 'Business Coaching', 'AL', 'booth', 'booth-a47@natcon.id'),
    ('B1', 'Bio Medika', 'Health & Wellness', 'BM', 'sponsor', 'booth-b1@natcon.id'),
    ('B2', 'Parahita Diagnostic Center', 'Health & Wellness Services', 'PD', 'sponsor', 'booth-b2@natcon.id'),
    ('B3', 'ProSnap', 'Business Consultant', 'P', 'sponsor', 'booth-b3@natcon.id'),
    ('C1', 'T Royal Medicalink Pharmalab & PT Aroma Bathi Indonesia', 'Pharmaceutical Manufacturing & Essential Oils', 'TR', 'sponsor', 'booth-c1@natcon.id')
) AS v (booth, company, category, initials, kind, email)
JOIN users u ON u.email = v.email
WHERE NOT EXISTS (SELECT 1 FROM tenants t WHERE t.booth = v.booth);

-- An exhibitor already on the floor plan under an older name or classification
-- follows the sheet: the committee edits there, not here.
UPDATE tenants t
SET name = v.company, category = v.category, initials = v.initials, kind = v.kind
FROM (VALUES
    ('A1', 'SSCX International', 'Management Consultant', 'SI', 'booth', 'booth-a1@natcon.id'),
    ('A2', 'PT. ORIENTAL LOGISTICS INDONESIA', 'Freight Forwarder', 'PO', 'booth', 'booth-a2@natcon.id'),
    ('A3', 'PT. Venamon', 'Manufacturer', 'PV', 'booth', 'booth-a3@natcon.id'),
    ('A4', 'ToffeeDev', 'SEO & Digital Marketing', 'T', 'booth', 'booth-a4@natcon.id'),
    ('A5', 'Doxadigital', 'Digital Advertising', 'D', 'booth', 'booth-a5@natcon.id'),
    ('A6', 'PT Natural Spirit', 'Healthy Organic Foods', 'PN', 'booth', 'booth-a6@natcon.id'),
    ('A9', 'PT. Gunanusa Eramandiri Tbk', 'Manufacturer specializing in premium nut products and high-quality fruit solutions', 'PG', 'booth', 'booth-a9@natcon.id'),
    ('A10', 'PT Tanamera Mitra Sentosa', 'Coffee Wholesale', 'PT', 'booth', 'booth-a10@natcon.id'),
    ('A14', 'WIT.id', 'IT Consultants', 'W', 'booth', 'booth-a14@natcon.id'),
    ('A15', 'PT ForBis Asia Indonesia', 'HRIS Software & Payroll Services', 'PF', 'booth', 'booth-a15@natcon.id'),
    ('A16', 'CV WIRABUANA SAKTI', 'automotive and stainless paint', 'CW', 'booth', 'booth-a16@natcon.id'),
    ('A17', 'One Tax CM Pte Ltd', 'Company Secretary', 'OT', 'booth', 'booth-a17@natcon.id'),
    ('A18 & A20', 'GrasiaCare', 'Profesional Service Health Care', 'G', 'booth', 'booth-a18@natcon.id'),
    ('A19', 'Sinar Printing (PT Sinar Media Kreasi)', 'Printer', 'SP', 'booth', 'booth-a19@natcon.id'),
    ('A22', 'Paper.id', 'B2B Digital Invoicing & Payment', 'P', 'booth', 'booth-a22@natcon.id'),
    ('A23', 'inHARMONY Preventive Clinic', 'Health & Wellness', 'IP', 'booth', 'booth-a23@natcon.id'),
    ('A24', 'PT Documenta Corpora Technology', 'Legal Service Plan', 'PD', 'booth', 'booth-a24@natcon.id'),
    ('A25', 'Lisanna Online Accounting & Tax Consultant', 'Accounting & Tax Consultant', 'LO', 'booth', 'booth-a25@natcon.id'),
    ('A27', 'PT Zona Kreatif Indonesia', 'IT Custom Software Development', 'PZ', 'booth', 'booth-a27@natcon.id'),
    ('A30', 'ICUBE (Invoice ke PT)', 'eCommerce Web and App Solution', 'I(', 'booth', 'booth-a30@natcon.id'),
    ('A31', 'PT. Norita Flexindo', 'Flexible Packaging', 'PN', 'booth', 'booth-a31@natcon.id'),
    ('A32', 'Alps Wills Pte Ltd', 'Will writing', 'AW', 'booth', 'booth-a32@natcon.id'),
    ('A33', 'BOOKINGTOGO', 'Travel Agent', 'B', 'booth', 'booth-a33@natcon.id'),
    ('A34', 'PAKS (MM2H) SDN BHD', 'MM2H', 'P(', 'booth', 'booth-a34@natcon.id'),
    ('A36', 'CV. TRIANA BINTANG', 'Manufactur dan Distributor GENSET', 'CT', 'booth', 'booth-a36@natcon.id'),
    ('A37', 'LEKA (PT Tissor Indonesia)', 'Retail - Electronics', 'L(', 'booth', 'booth-a37@natcon.id'),
    ('A38', 'CV IT Pro Solutions', 'Sales Force Automation', 'CI', 'booth', 'booth-a38@natcon.id'),
    ('A42', 'PT. TSN Ariestama Jaya', 'Office Supplies', 'PT', 'booth', 'booth-a42@natcon.id'),
    ('A43', 'PT. Creative Media Indonesia', 'Electronics Retailer', 'PC', 'booth', 'booth-a43@natcon.id'),
    ('A44', 'KETAPANG INDAH HOTEL', 'HOTEL', 'KI', 'booth', 'booth-a44@natcon.id'),
    ('A46', 'PT Belanja Segar Indonesia', 'Food Supplier', 'PB', 'booth', 'booth-a46@natcon.id'),
    ('A47 & A48', 'Alpha leaders', 'Business Coaching', 'AL', 'booth', 'booth-a47@natcon.id'),
    ('B1', 'Bio Medika', 'Health & Wellness', 'BM', 'sponsor', 'booth-b1@natcon.id'),
    ('B2', 'Parahita Diagnostic Center', 'Health & Wellness Services', 'PD', 'sponsor', 'booth-b2@natcon.id'),
    ('B3', 'ProSnap', 'Business Consultant', 'P', 'sponsor', 'booth-b3@natcon.id'),
    ('C1', 'T Royal Medicalink Pharmalab & PT Aroma Bathi Indonesia', 'Pharmaceutical Manufacturing & Essential Oils', 'TR', 'sponsor', 'booth-c1@natcon.id')
) AS v (booth, company, category, initials, kind, email)
WHERE t.booth = v.booth
  AND (t.name <> v.company OR t.category <> v.category OR t.kind <> v.kind);

-- Anything else that calls itself a booth or a sponsor is not on this floor
-- plan: leftovers from the sheet this migration replaces. The tenant row goes
-- first; its scanner login is behind a foreign key.
WITH removed AS (
    DELETE FROM tenants
    WHERE booth NOT IN ('A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A9', 'A10', 'A14', 'A15', 'A16', 'A17', 'A18 & A20', 'A19', 'A22', 'A23', 'A24', 'A25', 'A27', 'A30', 'A31', 'A32', 'A33', 'A34', 'A36', 'A37', 'A38', 'A42', 'A43', 'A44', 'A46', 'A47 & A48', 'B1', 'B2', 'B3', 'C1')
      AND NOT EXISTS (SELECT 1 FROM visits v WHERE v.tenant_id = tenants.id)
    RETURNING owner_user_id
)
DELETE FROM users u
USING removed r
WHERE u.id = r.owner_user_id AND u.role = 'tenant';
