-- The floor plan as the committee last drew it, and every exhibitor's logo.
--
-- Their logo pack names each file "<booth> - <company>.png", and those booth
-- numbers are not the ones the sheet this database was built from carries:
-- GrasiaCare has given up its second stand, and everything from Paper.id
-- onwards has moved down one slot. The committee's instruction was to follow
-- the pack's numbers, so this renumbers what 0023 seeded.
--
-- Matched on the COMPANY, because that is the one thing both lists agree on.
-- The scanner login follows the stand — booth-a20@natcon.id is whoever is
-- standing on A20 — so the logins are renamed with the numbers. Passwords are
-- untouched, and so is every scan already collected.
--
-- The logos ship with the app (frontend/public/logos, generated by
-- scripts/booth_logos.py) rather than living on the upload volume, so they
-- survive a redeploy. A logo the committee uploaded through the admin panel
-- is theirs and stays: only shipped paths and empty ones are rewritten.

CREATE TEMP TABLE floor_plan (company TEXT PRIMARY KEY, booth TEXT, logo TEXT) ON COMMIT DROP;

INSERT INTO floor_plan (company, booth, logo) VALUES
    ('SSCX International',                          'A1',      '/logos/sscx-international.png'),
    ('PT. ORIENTAL LOGISTICS INDONESIA',            'A2',      '/logos/oriental-logistics-indonesia.png'),
    ('PT. Venamon',                                 'A3',      '/logos/venamon.png'),
    ('ToffeeDev',                                   'A4',      '/logos/toffeedev.png'),
    ('Doxadigital',                                 'A5',      '/logos/doxadigital.png'),
    ('PT Natural Spirit',                           'A6',      '/logos/natural-spirit.png'),
    ('PT. Gunanusa Eramandiri Tbk',                 'A9',      '/logos/gunanusa-eramandiri.png'),
    ('PT Tanamera Mitra Sentosa',                   'A10',     '/logos/tanamera-mitra-sentosa.png'),
    ('WIT.id',                                      'A14',     '/logos/wit-id.png'),
    ('PT ForBis Asia Indonesia',                    'A15',     '/logos/forbis-asia-indonesia.png'),
    ('CV WIRABUANA SAKTI',                          'A16',     '/logos/wirabuana-sakti.png'),
    ('One Tax CM Pte Ltd',                          'A17',     '/logos/one-tax-cm.png'),
    ('GrasiaCare',                                  'A18',     '/logos/grasiacare.png'),
    ('Sinar Printing (PT Sinar Media Kreasi)',      'A19',     '/logos/sinar-printing-sinar.png'),
    ('Paper.id',                                    'A20',     '/logos/paper-id.png'),
    ('inHARMONY Preventive Clinic',                 'A22',     '/logos/inharmony-preventive-clinic.png'),
    ('PT Documenta Corpora Technology',             'A23',     '/logos/documenta-corpora-technology.png'),
    ('Lisanna Online Accounting & Tax Consultant',  'A24',     '/logos/lisanna-online-accounting.png'),
    ('PT Zona Kreatif Indonesia',                   'A25',     '/logos/zona-kreatif-indonesia.png'),
    ('ICUBE (Invoice ke PT)',                       'A27',     '/logos/icube.png'),
    ('PT. Norita Flexindo',                         'A30',     '/logos/norita-flexindo.png'),
    ('Alps Wills Pte Ltd',                          'A31',     '/logos/alps-wills.png'),
    ('BOOKINGTOGO',                                 'A32',     '/logos/bookingtogo.png'),
    ('PAKS (MM2H) SDN BHD',                         'A33',     '/logos/paks-mm2h.png'),
    ('CV. TRIANA BINTANG',                          'A34',     '/logos/triana-bintang.png'),
    ('LEKA (PT Tissor Indonesia)',                  'A37',     '/logos/leka-tissor-indonesia.png'),
    ('CV IT Pro Solutions',                         'A38',     '/logos/it-pro-solutions.png'),
    ('PT. TSN Ariestama Jaya',                      'A42',     '/logos/tsn-ariestama-jaya.png'),
    ('PT. Creative Media Indonesia',                'A43',     '/logos/creative-media-indonesia.png'),
    ('KETAPANG INDAH HOTEL',                        'A44',     '/logos/ketapang-indah-hotel.png'),
    ('PT Belanja Segar Indonesia',                  'A46',     '/logos/belanja-segar-indonesia.png'),
    ('Alpha leaders',                               'A47 & A48', '/logos/alpha-leaders.png'),
    -- The sponsors are not in the booth pack; these two sent a logo with the
    -- first one, and their stands keep the numbers the sheet gave them.
    ('Parahita Diagnostic Center',                             NULL, '/logos/parahita.png'),
    ('T Royal Medicalink Pharmalab & PT Aroma Bathi Indonesia', NULL, '/logos/royal-medicalink-pharmalab.png');

-- Logins first, in two passes: A22's crew moves to A20 while A20's old
-- occupant is still on it, so going straight to the final address would
-- collide on the staff-email index.
UPDATE users u
SET email = 'moving-' || u.id || '@natcon.id'
FROM tenants t JOIN floor_plan f ON f.company = t.name
WHERE u.id = t.owner_user_id AND f.booth IS NOT NULL AND t.booth <> f.booth;

UPDATE users u
SET email = 'booth-' ||
            lower(regexp_replace(split_part(f.booth, ' & ', 1), '[^A-Za-z0-9]', '', 'g')) ||
            '@natcon.id'
FROM tenants t JOIN floor_plan f ON f.company = t.name
WHERE u.id = t.owner_user_id AND u.email LIKE 'moving-%';

UPDATE tenants t
SET booth = f.booth
FROM floor_plan f
WHERE f.company = t.name AND f.booth IS NOT NULL AND t.booth <> f.booth;

UPDATE tenants t
SET logo_url = f.logo
FROM floor_plan f
WHERE f.company = t.name
  AND (t.logo_url = '' OR t.logo_url LIKE '/logos/%')
  AND t.logo_url <> f.logo;
