-- The networking floor: 90 tables of 10, matching the printed QR cards
-- ("Latest Natcon 2026 — QR Code Table.pdf", tables 1–90, "10 seats · scan
-- to join this table").
--
-- Tables used to be generated by hand on the admin Tables page. The cards
-- are now printed, and a printed card is a promise: TABLE:37 has to exist
-- and hold ten people on every database this system runs on, or somebody
-- standing at a real table scans a QR the app refuses. Master data that is
-- already on paper belongs in a migration, the same argument as the booths.
--
-- Idempotent the careful way: each table number is created only if absent,
-- and capacity is raised to 10 only where a smaller earlier value stands.
-- A capacity the committee deliberately edited above 10 is not touched, and
-- nothing is ever deleted here — a table with people checked in is not this
-- migration's to remove.

INSERT INTO networking_tables (table_no, hall, capacity)
SELECT g, '', 10
FROM generate_series(1, 90) AS g
WHERE NOT EXISTS (SELECT 1 FROM networking_tables t WHERE t.table_no = g);

UPDATE networking_tables
SET capacity = 10
WHERE table_no BETWEEN 1 AND 90
  AND capacity < 10;
