#!/usr/bin/env python3
"""Turn the committee's *Data Booth* sheet into the booth migration.

The booth list is event master data, so it lives in a migration: a laptop, a
staging box and production all end up with the same booths without anyone
remembering to import a spreadsheet.

    pip install openpyxl
    python3 scripts/booths_migration.py "~/Downloads/Data Booth ... .xlsx"

Rewrites backend/internal/repository/postgres/migrations/0014_booths.sql.
Re-run it whenever the sheet changes, then restart the API — booths that left
the sheet are removed (unless someone has already scanned them), and booths
that stayed keep their login and their scans.

Expected columns: Booth Number · Name · BNI Chapter · Company Name ·
Business Classification. That is the ticketing team's own export, unedited.
"""

import pathlib
import sys

import openpyxl

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "backend/internal/repository/postgres/migrations/0014_booths.sql"

PLACEHOLDER_HASH = "$2a$10$SEEDPLACEHOLDERSEEDPLACEHOLDERSEEDPLACEHOLDERSEEDPLACEH"


def initials(name: str) -> str:
    """Mirror of tenantInitials in the Go usecase, so a booth created here and
    one created through the admin panel look the same."""
    out = "".join(w[0] for w in name.split())
    return out[:2].upper()


def login_email(booth: str) -> str:
    return f"booth-{booth.replace('-', '').lower()}@natcon.id"


def q(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def read_booths(path: pathlib.Path):
    ws = openpyxl.load_workbook(path, read_only=True).worksheets[0]
    rows = list(ws.iter_rows(values_only=True))
    header = [str(h).strip() if h else "" for h in rows[0]]
    col = {h: i for i, h in enumerate(header)}
    for needed in ("Booth Number", "Company Name"):
        if needed not in col:
            sys.exit(f"column {needed!r} missing — got {header}")

    booths, seen = [], set()
    for r in rows[1:]:
        def cell(name):
            i = col.get(name)
            return str(r[i]).strip() if i is not None and r[i] is not None else ""

        booth, company = cell("Booth Number"), cell("Company Name")
        if not booth or not company or booth in seen:
            continue
        seen.add(booth)
        booths.append({
            "booth": booth,
            "company": company,
            "category": cell("Business Classification"),
            "contact": cell("Name"),
            "chapter": cell("BNI Chapter"),
            "initials": initials(company),
            "email": login_email(booth),
        })
    return booths


def values_block(booths) -> str:
    lines = []
    for b in booths:
        lines.append("    (" + ", ".join(q(b[k]) for k in
                     ("booth", "company", "category", "initials", "contact", "chapter", "email")) + ")")
    return ",\n".join(lines)


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    src = pathlib.Path(sys.argv[1]).expanduser()
    booths = read_booths(src)
    if not booths:
        sys.exit("no booth rows found")

    block = values_block(booths)
    codes = ", ".join(q(b["booth"]) for b in booths)

    sql = f"""-- The {len(booths)} booths from the committee's "Data Booth" sheet.
-- GENERATED by scripts/booths_migration.py — edit the sheet, not this file.
--
-- Idempotent in both directions:
--   · a booth already present under its code is left alone, keeping its
--     scanner login and every scan it has collected;
--   · a booth that is NOT in the sheet is removed, but only when nobody has
--     scanned it — a database in use is never quietly emptied.
--
-- Scanner accounts land on the default password (booth-<code>@natcon.id /
-- SEED_PASSWORD): the row below carries a placeholder hash nobody can sign in
-- with, and the API's seeder rewrites it on the next start. Set
-- SEED_PASSWORD before the event.

-- Scanner logins first: one tenant user per booth.
INSERT INTO users (name, email, password_hash, role, company)
SELECT v.company, v.email, '{PLACEHOLDER_HASH}', 'tenant', v.company
FROM (VALUES
{block}
) AS v (booth, company, category, initials, contact, chapter, email)
WHERE NOT EXISTS (SELECT 1 FROM users u WHERE u.email = v.email)
  AND NOT EXISTS (SELECT 1 FROM tenants t WHERE t.booth = v.booth);

INSERT INTO tenants (name, category, booth, initials, kind, description,
                     contact_name, chapter, owner_user_id)
SELECT v.company, v.category, v.booth, v.initials, 'booth', '',
       v.contact, v.chapter, u.id
FROM (VALUES
{block}
) AS v (booth, company, category, initials, contact, chapter, email)
JOIN users u ON u.email = v.email
WHERE NOT EXISTS (SELECT 1 FROM tenants t WHERE t.booth = v.booth);

-- Anything else that calls itself a booth is not on the floor plan: leftovers
-- from an older sheet or a mockup. Sponsors are left alone — they never came
-- from this sheet. The tenant row goes first; its scanner login is behind a
-- foreign key.
WITH removed AS (
    DELETE FROM tenants
    WHERE kind = 'booth'
      AND booth NOT IN ({codes})
      AND NOT EXISTS (SELECT 1 FROM visits v WHERE v.tenant_id = tenants.id)
    RETURNING owner_user_id
)
DELETE FROM users u
USING removed r
WHERE u.id = r.owner_user_id AND u.role = 'tenant';
"""
    OUT.write_text(sql, encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)} — {len(booths)} booths from {src.name}")
    print("  " + ", ".join(b["booth"] for b in booths))


if __name__ == "__main__":
    main()
